### DISCUSSION TITLE
Openmemory MCP using remote Qdrant

### DISCUSSION THREAD

**Discussion by cakriwut** [mem0ai/mem0#2886] [Q&A]
I am trying to use remote QDRANT in openmemory-mcp but always failed. Anyone has solution?
```yaml
openmemory_mcp:
    image: mem0/openmemory-mcp:latest
    environment:
      - OPENAI_API_KEY=sk-xx
      - USER=${USER}
      - QDRANT_URL=https://*****.cloud.qdrant.io:6333
      - QDRANT_API_KEY=ey.....
```
