### ISSUE TITLE
How to use custom OLLAMA created model?

### ISSUE THREAD

**Issue by Japkeerat** [mem0ai/mem0#1671]
I already have a custom model built using OLLAMA's modelfile which pulls LLAMA3.1 and adds custom system prompt and template to it.

How do I use this model?

If I provide the name of this model in the config as shown below, it tries to fetch from the OLLAMA instead of picking up from the locally present version.

```
llm:
  provider: ollama
  config:
    model: 'Custom:0.1.0'
    temperature: 0.5
    top_p: 1
    stream: True
    base_url: 'http://localhost:11434'
embedder:
  provider: ollama
  config:
    model: mxbai-embed-large
    base_url: 'http://localhost:11434'

```

What is the right way to perform this action? Cannot find anything from the documentation. Perhaps I could write its documentation once I find the answer.
