### ISSUE TITLE
disable telemetry

### ISSUE THREAD

**Issue by sysadmin-info** [mem0ai/mem0#2683]
### 🚀 The feature

To disable telemetry in the `openmemory` project, you need to configure the environment variables appropriately in the `.env` files and the `docker-compose.yml` file. Here are the steps you can take:

---

### ✅ 1. Set the `TELEMETRY_DISABLED=true` variable

In the `.env` file located in the root directory of the project (`~/mem0/openmemory/.env`), there should be an additional line:

```env
TELEMETRY_DISABLED=true
````

Make sure this variable is also present in the `api/.env` file, since the `openmemory-mcp` service uses that file as the source of its environment variables. If it’s missing, add:

```env
TELEMETRY_DISABLED=true
```

---

### ✅ 2. Set the `NEXT_TELEMETRY_DISABLED=1` variable for Next.js

The user interface (`openmemory-ui`), built with Next.js, collects anonymous telemetry data by default. To disable it, add the following line to the `ui/.env` file:

```env
NEXT_TELEMETRY_DISABLED=1
```

Then, ensure this variable is passed to the container in the `docker-compose.yml` file. In the `openmemory-ui` service section, add it to the list of environment variables:

```yaml
services:
  openmemory-ui:
    ...
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}
      - NEXT_TELEMETRY_DISABLED=1
```

---

### ✅ 3. Rebuild and restart the containers

After making the above changes, rebuild and restart the containers so the new settings are applied:

```bash
docker compose down
docker compose up --build -d
```

### Motivation, pitch

For me telemetry is something that is unecessary. Simple as that.
