### ISSUE TITLE
OpenMemory: Windows Issues - entrypoint.sh breaks due to CRLF, port 3000 conflicts (see workarounds)

### ISSUE THREAD

**Issue by ThoughtPhotography** [mem0ai/mem0#2690]
### 🐛 Describe the bug

After a lot of frustration I finally got this working.

### Issues:
**1)** Make is a prerequisite. 99.9% of Win users won't know what it is and will need to install it.
**2)** Port 3000 is far too common. A different default should be used to avoid conflicts (e.g. Open WebUI).

### Workaround:
- Modify docker-compose to use any other port (3001 in this case).
- Dockerfile in **UI** directory also uses port 3000.
- Adding environment: PORT=3001 overrides this (otherwise Dockerfile also needs editing)
```
openmemory-ui:
  build:
    context: ui/
    dockerfile: Dockerfile
  image: mem0/openmemory-ui:latest
  ports:
    - "3001:3001"  # Map host port 3001 to container port 3001
  environment:
    - PORT=3001    # This overrides ENV PORT in the Dockerfile for this container instance
    - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    - NEXT_PUBLIC_USER_ID=${USER}
  # Add other configurations as needed
```
**3)** After fixing that, the UI container still likely won't run due to the following Docker error:
> exec /home/nextjs/entrypoint.sh: no such file or directory

This is due to problems with the line endings.
Windows uses CRLF (Carriage Return + Line Feed) line endings, while Linux expects LF (Line Feed). 

`git config --global core.autocrlf true`

Is the default setting on Windows which changes files to CRLF line-endings when you clone/pull, so the Linux shell inside the container misinterprets the path to the script or its interpreter in entrypoint.sh, leading to the "no such file or directory" error.

### Workaround:
- Open entrypoint.sh in your IDE (or any decent text editor)
- In Cursor, etc. this is in the bottom right.
![Image](https://github.com/user-attachments/assets/63b7f735-5d89-4d47-a90c-c58be4c1f9ae)
- Click it, change to LF, and resave the file.
- If you already have a non-functional openmemory container in Docker, delete it, and start fresh.
- After running make build and make up (**using bash**), everything should work. 
 
Hopefully that helps any fellow Windows users having the same problems...
